site_name: MBD Assignment Docs
repo_url: https://github.com/ManiVannan97/MBD-Assignment
repo_name: MBD-Assignment
site_author: yogeshvar
nav:
  - Home: index.md
  - Assignment 1: assign1.md
  - Assignment 2: assign2.md
theme: readthedocs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
